# Site settings
title: Lucy M Li
email: ml3109@ic.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Infectious disease epidemiologist using and developing phylodynamic methods. R markdown enthusiast.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: lucylmq
github_username:  lucymli

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/


