# WhatATheme
markdown: kramdown

# URL of the Site
url: https://lucymli.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: lucymli.com

# Title of the Site
title: Lucy M Li
# Description of the Site
description: Lucy M Li | Personal Website
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lucy@lucymli.com
twitter_username: 
linkedin_username: lucymli
github_username:  lucymli
gscholar_username: WJdo42cAAAAJ
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Lucy M Li
# URL for the Image of the Author
author-image: assets/images/lucymli_headshot.jpg
# 60 Words About the Author
author-about: Data Scientist specializing in healthcare and public health.
# Longer About for the Author
author-about-long: 
  
  * Senior data scientist based in the San Francisco Bay Area available for consulting and short-term projects.
  * Interests include [mathematical modeling](https://scholar.google.com/citations?hl=en&user=WJdo42cAAAAJ), [machine learning](https://www.fastcompany.com/90523073/how-many-covid-infections-are-undetected-studying-its-mutations-may-hold-the-answer), integrating data sources, and geospatial analysis.
  * PhD and postdoctoral research experience at Imperial College London and Harvard University in public health/healthcare, specializing in infectious diseases.
  * Prior full-time work experience in academic, non-profit, and technology organizations.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: lucymli.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
