- menu_name: "Contact"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"


- name: "sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
